- block:
    - name: Install required packages (DNF)
      become: true
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        "{{ required_packages }}"
      when: ansible_pkg_mgr == 'dnf'
    - name: Install required packages (YUM)
      become: true
      yum:
        name: "{{ item }}"
        state: present
      loop:
        "{{ required_packages }}"
      when: ansible_pkg_mgr == 'yum'
  tags:
    - amq::required_packages
