# KAFKA ALL-IN-ONE INSTALLATION PLAYBOOK

- hosts: kafka_node
  remote_user: root
  become: true
  any_errors_fatal: true

  pre_tasks:
    - include_vars:
        file: "common"
    - include_vars:
        file: "environments/dev"
    - include_vars:
        file: "credentials/customerportal"
  roles:
    - kafka-aio-broker
